module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    extend: {
      colors: {
        greentea: { default: '#33F20D', 100: '#D6FCCF', 200: '#ADFA9E', 300: '#85F76E', 400: '#5CF53D', 500: '#33F20D', 600: '#29C20A', 700: '#1F9108', 800: '#146105', 900: '#0A3003' }
      },
      spacing: {
        72: '18rem',
        50: '13rem',
        80: '36rem'
      },
      fontFamily: {
        table: ['Nunito', 'sans-serif']
      }
    }
  },
  variants: {
    accessibility: ['responsive', 'focus', 'group-hover'],
    alignContent: ['responsive', 'group-hover'],
    alignItems: ['responsive', 'group-hover'],
    alignSelf: ['responsive', 'group-hover'],
    appearance: ['responsive', 'group-hover'],
    backgroundAttachment: ['responsive', 'group-hover'],
    backgroundClip: ['responsive', 'group-hover'],
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundImage: ['responsive', 'group-hover'],
    gradientColorStops: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundOpacity: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundPosition: ['responsive', 'group-hover'],
    backgroundRepeat: ['responsive', 'group-hover'],
    backgroundSize: ['responsive', 'group-hover'],
    borderCollapse: ['responsive', 'group-hover'],
    borderColor: ['responsive', 'hover', 'focus', 'group-hover'],
    borderOpacity: ['responsive', 'hover', 'focus', 'group-hover'],
    borderRadius: ['responsive', 'group-hover'],
    borderStyle: ['responsive', 'group-hover'],
    borderWidth: ['responsive', 'group-hover'],
    boxShadow: ['responsive', 'hover', 'focus', 'group-hover'],
    boxSizing: ['responsive', 'group-hover'],
    container: ['responsive', 'group-hover'],
    cursor: ['responsive', 'group-hover'],
    display: ['responsive', 'group-hover'],
    divideColor: ['responsive', 'group-hover'],
    divideOpacity: ['responsive', 'group-hover'],
    divideStyle: ['responsive', 'group-hover'],
    divideWidth: ['responsive', 'group-hover'],
    fill: ['responsive', 'group-hover'],
    flex: ['responsive', 'group-hover'],
    flexDirection: ['responsive', 'group-hover'],
    flexGrow: ['responsive', 'group-hover'],
    flexShrink: ['responsive', 'group-hover'],
    flexWrap: ['responsive', 'group-hover'],
    float: ['responsive', 'group-hover'],
    clear: ['responsive', 'group-hover'],
    fontFamily: ['responsive', 'group-hover'],
    fontSize: ['responsive', 'group-hover'],
    fontSmoothing: ['responsive', 'group-hover'],
    fontVariantNumeric: ['responsive', 'group-hover'],
    fontStyle: ['responsive', 'group-hover'],
    fontWeight: ['responsive', 'hover', 'focus', 'group-hover'],
    height: ['responsive', 'group-hover'],
    inset: ['responsive', 'group-hover'],
    justifyContent: ['responsive', 'group-hover'],
    justifyItems: ['responsive', 'group-hover'],
    justifySelf: ['responsive', 'group-hover'],
    letterSpacing: ['responsive', 'group-hover'],
    lineHeight: ['responsive', 'group-hover'],
    listStylePosition: ['responsive', 'group-hover'],
    listStyleType: ['responsive', 'group-hover'],
    margin: ['responsive', 'group-hover'],
    maxHeight: ['responsive', 'group-hover'],
    maxWidth: ['responsive', 'group-hover'],
    minHeight: ['responsive', 'group-hover'],
    minWidth: ['responsive', 'group-hover'],
    objectFit: ['responsive', 'group-hover'],
    objectPosition: ['responsive', 'group-hover'],
    opacity: ['responsive', 'hover', 'focus', 'group-hover'],
    order: ['responsive', 'group-hover'],
    outline: ['responsive', 'focus', 'group-hover'],
    overflow: ['responsive', 'group-hover'],
    overscrollBehavior: ['responsive', 'group-hover'],
    padding: ['responsive', 'group-hover'],
    placeContent: ['responsive', 'group-hover'],
    placeItems: ['responsive', 'group-hover'],
    placeSelf: ['responsive', 'group-hover'],
    placeholderColor: ['responsive', 'focus', 'group-hover'],
    placeholderOpacity: ['responsive', 'focus', 'group-hover'],
    pointerEvents: ['responsive', 'group-hover'],
    position: ['responsive', 'group-hover'],
    resize: ['responsive', 'group-hover'],
    space: ['responsive', 'group-hover'],
    stroke: ['responsive', 'group-hover'],
    strokeWidth: ['responsive', 'group-hover'],
    tableLayout: ['responsive', 'group-hover'],
    textAlign: ['responsive', 'group-hover'],
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    textOpacity: ['responsive', 'hover', 'focus', 'group-hover'],
    textDecoration: ['responsive', 'hover', 'focus', 'group-hover'],
    textTransform: ['responsive', 'group-hover'],
    userSelect: ['responsive', 'group-hover'],
    verticalAlign: ['responsive', 'group-hover'],
    visibility: ['responsive', 'group-hover'],
    whitespace: ['responsive', 'group-hover'],
    width: ['responsive', 'group-hover'],
    wordBreak: ['responsive', 'group-hover'],
    zIndex: ['responsive', 'group-hover'],
    gap: ['responsive', 'group-hover'],
    gridAutoFlow: ['responsive', 'group-hover'],
    gridTemplateColumns: ['responsive', 'group-hover'],
    gridAutoColumns: ['responsive', 'group-hover'],
    gridColumn: ['responsive', 'group-hover'],
    gridColumnStart: ['responsive', 'group-hover'],
    gridColumnEnd: ['responsive', 'group-hover'],
    gridTemplateRows: ['responsive', 'group-hover'],
    gridAutoRows: ['responsive', 'group-hover'],
    gridRow: ['responsive', 'group-hover'],
    gridRowStart: ['responsive', 'group-hover'],
    gridRowEnd: ['responsive', 'group-hover'],
    transform: ['responsive', 'hover', 'focus', 'group-hover'],
    transformOrigin: ['responsive', 'group-hover'],
    scale: ['responsive', 'hover', 'focus', 'group-hover'],
    rotate: ['responsive', 'hover', 'focus', 'group-hover'],
    translate: ['responsive', 'hover', 'focus', 'group-hover'],
    skew: ['responsive', 'hover', 'focus', 'group-hover'],
    transitionProperty: ['responsive', 'hover', 'focus', 'group-hover'],
    transitionTimingFunction: ['responsive', 'hover', 'focus', 'group-hover'],
    transitionDuration: ['responsive', 'hover', 'focus', 'group-hover'],
    transitionDelay: ['responsive', 'hover', 'focus', 'group-hover'],
    animation: ['responsive', 'hover', 'focus']
  },
  plugins: []
}
